<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="2" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="178621" started-at="2022-03-30T03:12:20 EDT" finished-at="2022-03-30T03:15:18 EDT">
    <groups>
      <group name="Regression">
        <method signature="MyPortfolioTest.openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="openPortfolioTest" class="com.pom.framework.testcases.MyPortfolioTest"/>
      </group> <!-- Regression -->
      <group name="LoginTest">
        <method signature="MyPortfolioTest.openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="openPortfolioTest" class="com.pom.framework.testcases.MyPortfolioTest"/>
      </group> <!-- LoginTest -->
    </groups>
    <test name="Default test" duration-ms="178621" started-at="2022-03-30T03:12:20 EDT" finished-at="2022-03-30T03:15:18 EDT">
      <class name="com.pom.framework.testcases.MyPortfolioTest">
        <test-method status="FAIL" signature="openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="openPortfolioTest" duration-ms="57373" started-at="2022-03-30T03:12:21 EDT" data-provider="getOpenPortfolioTestData" finished-at="2022-03-30T03:13:18 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email Address=anshulc55, Password=Test@1234, Page Title=Rediff Moneywiz | My Portfolio(s), Comments=Valid Credentials}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[target frame detached
  (Session info: MicrosoftEdge=99.0.1150.55)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'RTSUBHRO-PC', ip: '192.168.86.24', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_281'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [539e731da888457b05d229003f2db794, executeScript {script=return window.jQuery != undefined && jQuery.active == 0;, args=[]}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 99.0.1150.55, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:51331}, msedge: {msedgedriverVersion: 99.0.1150.55 (c8275fcfc2e02..., userDataDir: C:\Users\rtsubhro\AppData\L...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51331/devtoo..., se:cdpVersion: 99.0.1150.55, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 539e731da888457b05d229003f2db794]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: target frame detached
  (Session info: MicrosoftEdge=99.0.1150.55)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'RTSUBHRO-PC', ip: '192.168.86.24', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_281'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [539e731da888457b05d229003f2db794, executeScript {script=return window.jQuery != undefined && jQuery.active == 0;, args=[]}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 99.0.1150.55, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:51331}, msedge: {msedgedriverVersion: 99.0.1150.55 (c8275fcfc2e02..., userDataDir: C:\Users\rtsubhro\AppData\L...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51331/devtoo..., se:cdpVersion: 99.0.1150.55, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 539e731da888457b05d229003f2db794
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:492)
at com.pom.framework.baseclasses.BaseTestClass.waitForPageLoad(BaseTestClass.java:129)
at com.pom.framework.pageclasses.PortfolioLoginPage.doLogin(PortfolioLoginPage.java:58)
at com.pom.framework.testcases.MyPortfolioTest.openPortfolioTest(MyPortfolioTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPortfolioTest -->
        <test-method status="PASS" signature="SetTestResult(org.testng.ITestResult)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="SetTestResult" is-config="true" duration-ms="7705" started-at="2022-03-30T03:13:18 EDT" finished-at="2022-03-30T03:13:26 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openPortfolioTest status=FAILURE method=MyPortfolioTest.openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetTestResult -->
        <test-method status="FAIL" signature="openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="openPortfolioTest" duration-ms="34852" started-at="2022-03-30T03:13:26 EDT" data-provider="getOpenPortfolioTestData" finished-at="2022-03-30T03:14:01 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email Address=anshulc5, Password=Test@1234, Page Title=Indian stock markets: Login to Portfolio, Comments=Invalid Email Address}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failed for Money Portfolio]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failed for Money Portfolio
at org.testng.Assert.fail(Assert.java:99)
at com.pom.framework.baseclasses.BasePageClass.reportFail(BasePageClass.java:142)
at com.pom.framework.pageclasses.PortfolioLoginPage.doLogin(PortfolioLoginPage.java:62)
at com.pom.framework.testcases.MyPortfolioTest.openPortfolioTest(MyPortfolioTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPortfolioTest -->
        <test-method status="PASS" signature="SetTestResult(org.testng.ITestResult)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="SetTestResult" is-config="true" duration-ms="578" started-at="2022-03-30T03:14:01 EDT" finished-at="2022-03-30T03:14:02 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openPortfolioTest status=FAILURE method=MyPortfolioTest.openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetTestResult -->
        <test-method status="FAIL" signature="openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="openPortfolioTest" duration-ms="41818" started-at="2022-03-30T03:14:02 EDT" data-provider="getOpenPortfolioTestData" finished-at="2022-03-30T03:14:43 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email Address=anshulc55, Password=Test@12345, Page Title=Indian stock markets: Login to Portfolio, Comments=Invalid Password}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failed for Money Portfolio]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failed for Money Portfolio
at org.testng.Assert.fail(Assert.java:99)
at com.pom.framework.baseclasses.BasePageClass.reportFail(BasePageClass.java:142)
at com.pom.framework.pageclasses.PortfolioLoginPage.doLogin(PortfolioLoginPage.java:62)
at com.pom.framework.testcases.MyPortfolioTest.openPortfolioTest(MyPortfolioTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPortfolioTest -->
        <test-method status="PASS" signature="SetTestResult(org.testng.ITestResult)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="SetTestResult" is-config="true" duration-ms="1339" started-at="2022-03-30T03:14:43 EDT" finished-at="2022-03-30T03:14:45 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openPortfolioTest status=FAILURE method=MyPortfolioTest.openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetTestResult -->
        <test-method status="FAIL" signature="openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="openPortfolioTest" duration-ms="31589" started-at="2022-03-30T03:14:45 EDT" data-provider="getOpenPortfolioTestData" finished-at="2022-03-30T03:15:16 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email Address=anshulc5, Password=Test@12345, Page Title=Indian stock markets: Login to Portfolio, Comments=Invalid Credentials}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failed for Money Portfolio]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failed for Money Portfolio
at org.testng.Assert.fail(Assert.java:99)
at com.pom.framework.baseclasses.BasePageClass.reportFail(BasePageClass.java:142)
at com.pom.framework.pageclasses.PortfolioLoginPage.doLogin(PortfolioLoginPage.java:62)
at com.pom.framework.testcases.MyPortfolioTest.openPortfolioTest(MyPortfolioTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPortfolioTest -->
        <test-method status="PASS" signature="SetTestResult(org.testng.ITestResult)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="SetTestResult" is-config="true" duration-ms="1058" started-at="2022-03-30T03:15:16 EDT" finished-at="2022-03-30T03:15:17 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openPortfolioTest status=FAILURE method=MyPortfolioTest.openPortfolioTest(java.util.Hashtable)[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetTestResult -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:com.pom.framework.testcases.MyPortfolioTest@e1e309]" name="quitBrowser" is-config="true" duration-ms="825" started-at="2022-03-30T03:15:17 EDT" finished-at="2022-03-30T03:15:18 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.pom.framework.testcases.MyPortfolioTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
